name: Long workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Avoir le code du repertoire
              uses: actions/checkout@v3
            - name: Installer node js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Installer les dependences
              run: npm ci
            - name: Run tests
              run: npm test
